/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOG_H_RPCGEN
#define _LOG_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct log_operation_args {
	char *user;
	char *operation;
};
typedef struct log_operation_args log_operation_args;

struct log_sendattach_args {
	char *user;
	char *operation;
	char *filename;
};
typedef struct log_sendattach_args log_sendattach_args;

#define LOGPROG 0x20000001
#define LOGVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define log_operation 1
extern  enum clnt_stat log_operation_1(log_operation_args *, int *, CLIENT *);
extern  bool_t log_operation_1_svc(log_operation_args *, int *, struct svc_req *);
#define log_sendattach 2
extern  enum clnt_stat log_sendattach_1(log_sendattach_args *, int *, CLIENT *);
extern  bool_t log_sendattach_1_svc(log_sendattach_args *, int *, struct svc_req *);
extern int logprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define log_operation 1
extern  enum clnt_stat log_operation_1();
extern  bool_t log_operation_1_svc();
#define log_sendattach 2
extern  enum clnt_stat log_sendattach_1();
extern  bool_t log_sendattach_1_svc();
extern int logprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_operation_args (XDR *, log_operation_args*);
extern  bool_t xdr_log_sendattach_args (XDR *, log_sendattach_args*);

#else /* K&R C */
extern bool_t xdr_log_operation_args ();
extern bool_t xdr_log_sendattach_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOG_H_RPCGEN */
