/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "/home/alexelnegro/Documents/University files/3rd year/2o cuatri/Sistemas distribuidos/repo - Practica-Final-Distribuidos/log.h"

bool_t
xdr_log_operation_args (XDR *xdrs, log_operation_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_log_sendattach_args (XDR *xdrs, log_sendattach_args *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->filename, ~0))
		 return FALSE;
	return TRUE;
}
