/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "/home/alexelnegro/Documents/University files/3rd year/2o cuatri/Sistemas distribuidos/repo - Practica-Final-Distribuidos/log.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
log_operation_1(log_operation_args *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, log_operation,
		(xdrproc_t) xdr_log_operation_args, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
log_sendattach_1(log_sendattach_args *argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, log_sendattach,
		(xdrproc_t) xdr_log_sendattach_args, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
